### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: sun/jvm/hotspot/tools/Tool

### ISSUE THREAD

**Issue by omegabr22** [cookiedragon234/JvmClassDumper#3]
````Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: sun/jvm/hotspot/tools/Tool
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: sun.jvm.hotspot.tools.Tool
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more

**Comment by cookiedragon234** [comment]
1. Please dont open duplicate issues or I will ban you from the repository
2. If you had read the ReadMe you would see that you need to include a path to the JDK in the classpath. Since I have a jdk installed at `C:\Program Files\Java\jdk1.8.0_241\` I will run the dumper like so:
```
java -cp "C:\Program Files\Java\jdk1.8.0_241\lib\*;D:\Computing\dumper\build\libs\*;" cookiedragon.dumper.EntryPoint list vm```

You will need to replace it with the path to your own jdk.
